export default [
    {
        "id": 3438,
        "text": "short answer type",
        "description": "check if the company is listed in the country of registration",
        "sourceType": 0,
        "formId": 79,
        "atom": 1,
        "required": true,
        "validationRules": "",
        "respType": "SHORT_ANSWER",
        "customerResponse": "",
        "responseOptions": "",
        "responseConditions": "",
        "seq": 1,
        "changed": false,
        "addOther": false,
        "fromTemplate": false,
        "status": "ACTIVE",
        "type": "QUESTION",
        "createdOn": "2019-02-05T00:57:16",
        "updatedOn": "2019-02-05T01:02:44"
    },
    {
        "id": 3439,
        "text": "multiple choice type",
        "description": "check if the customer is a listed company",
        "sourceType": 0,
        "formId": 79,
        "atom": 2,
        "required": true,
        "validationRules": "",
        "respType": "MULTIPLE_CHOICE",
        "customerResponse": "",
        "responseOptions": "{\"answer_options\":[\"multiple choice 1\",\"multiple choice 2\"],\"add_other\":true}",
        "responseConditions": "",
        "seq": 2,
        "changed": false,
        "addOther": false,
        "fromTemplate": false,
        "status": "ACTIVE",
        "type": "QUESTION",
        "createdOn": "2019-02-05T00:57:16",
        "updatedOn": "2019-02-05T01:02:44"
    }
];